
-- Generated by ORDS REST Data Services 25.4.0.r3441128
-- Schema: DEMO_FACTORY_ADMIN  Date: Sun Feb 08 05:18:24 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo_factory_admin',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'DEMO_FACTORY_API',
      p_base_path      => '/demo_factory/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'DEMO_FACTORY_API',
      p_pattern        => 'health',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'DEMO_FACTORY_API',
      p_pattern        => 'health',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select ''ok'' as status, systimestamp as db_time from dual');


COMMIT;

END;