
-- Generated by ORDS REST Data Services 25.4.0.r3441128
-- Schema: DEMO_FACTORY_ADMIN  Date: Sun Feb 08 06:18:43 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo_factory_admin',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'DEMO_FACTORY_API',
      p_base_path      => '/demo_factory/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'DEMO_FACTORY_API',
      p_pattern        => 'health',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'DEMO_FACTORY_API',
      p_pattern        => 'health',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select ''ok'' as status, systimestamp as db_time from dual');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'DEMO_FACTORY_API',
      p_pattern        => 'runs/:run_id/step',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'DEMO_FACTORY_API',
      p_pattern        => 'runs/:run_id/step',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'declare
  l_body        clob := :body_text;
  l_run_id      varchar2(36) := :run_id;

  l_step_key    varchar2(200);
  l_status      varchar2(30);
  l_message     varchar2(4000);
  l_attempt_inc number;
  l_details     clob;
begin
  l_step_key := json_value(l_body, ''$.step_key'' returning varchar2(200) null on error null on empty);
  l_status   := json_value(l_body, ''$.status''   returning varchar2(30)  null on error null on empty);
  l_message  := json_value(l_body, ''$.message''  returning varchar2(4000) null on error null on empty);

  l_attempt_inc := json_value(
    l_body,
    ''$.attempt_inc''
    returning number
    default 0 on error
    default 0 on empty
  );

  l_details := json_query(l_body, ''$.details_json'' returning clob null on error null on empty);

  if l_step_key is null then
    raise_application_error(-20010, ''Missing step_key'');
  end if;

  if l_status is null then
    raise_application_error(-20011, ''Missing status'');
  end if;

  pkg_' || 'demo_factory_runs.upsert_step(
    p_run_id       => l_run_id,
    p_step_key     => l_step_key,
    p_status       => l_status,
    p_message      => l_message,
    p_attempt_inc  => nvl(l_attempt_inc, 0),
    p_details_json => l_details
  );

  owa_util.mime_header(''application/json'', false);
  owa_util.http_header_close;
  htp.p(''{"ok":true}'');
end;');


COMMIT;

END;